name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # `libgtk2.0-0` and `libxt6` are required by an older version of Firefox.
    - name: Install Required System Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev ubuntu-restricted-extras xvfb libxml2-dev libxslt-dev python3-dev libevent-dev python3-pip python3-venv gettext libgtk2.0-0 libxt6

    - name: Install Dependencies
      run: make requirements

    - name: Check if translations are up-to-date
      run: make check_translations_up_to_date

    - name: Run quality checks
      run: make test.quality

    - name: Run unit tests
      run: make test.unit
